
modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All Rights Reserved"
issueTrackerURL="https://github.com/ISenseHostility/Food-Enhancements/issues"

[[mods]] #mandatory
    modId="food_enhancements" #mandatory
    version="1.19.2-1.12.0" #mandatory
    displayName="Food Enhancements" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/food-enhancements"
    logoFile="food_enhancements.png" #optional
    authors="ISenseHostility" #optional
    description='''
    Food Enhancements adds some vanilla-friendly foods to the game!
    '''

[[dependencies.food_enhancements]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.food_enhancements]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, )"
    ordering="NONE"
    side="BOTH"
